# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cmitd\Documents\PycharmProjects\exhibion\vievs\maintesr.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MonitorManagment(object):
    def setupUi(self, MonitorManagment):
        MonitorManagment.setObjectName("MonitorManagment")
        MonitorManagment.setEnabled(True)
        MonitorManagment.resize(1000, 700)
        MonitorManagment.setMinimumSize(QtCore.QSize(1000, 700))
        MonitorManagment.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MonitorManagment)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(441, 81, 500, 400))
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 400))
        self.graphicsView.setMaximumSize(QtCore.QSize(500, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.ProjectorIndicator = QtWidgets.QRadioButton(self.centralwidget)
        self.ProjectorIndicator.setEnabled(False)
        self.ProjectorIndicator.setGeometry(QtCore.QRect(52, 127, 77, 17))
        self.ProjectorIndicator.setObjectName("ProjectorIndicator")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(52, 82, 140, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.buttonDialogProjector = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonDialogProjector.setGeometry(QtCore.QRect(52, 150, 156, 23))
        self.buttonDialogProjector.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonDialogProjector.setObjectName("buttonDialogProjector")
        self.buttonDialogScreen_3 = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonDialogScreen_3.setEnabled(True)
        self.buttonDialogScreen_3.setGeometry(QtCore.QRect(244, 400, 156, 23))
        self.buttonDialogScreen_3.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonDialogScreen_3.setObjectName("buttonDialogScreen_3")
        self.buttonDialogScreen_2 = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonDialogScreen_2.setEnabled(True)
        self.buttonDialogScreen_2.setGeometry(QtCore.QRect(244, 371, 156, 23))
        self.buttonDialogScreen_2.setMouseTracking(True)
        self.buttonDialogScreen_2.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonDialogScreen_2.setObjectName("buttonDialogScreen_2")
        self.ScreenIndicator_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_2.setEnabled(False)
        self.ScreenIndicator_2.setGeometry(QtCore.QRect(52, 371, 121, 17))
        self.ScreenIndicator_2.setObjectName("ScreenIndicator_2")
        self.ScreenIndicator_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_1.setEnabled(False)
        self.ScreenIndicator_1.setGeometry(QtCore.QRect(52, 342, 131, 17))
        self.ScreenIndicator_1.setObjectName("ScreenIndicator_1")
        self.ScreenIndicator_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_3.setEnabled(False)
        self.ScreenIndicator_3.setGeometry(QtCore.QRect(52, 400, 121, 17))
        self.ScreenIndicator_3.setObjectName("ScreenIndicator_3")
        self.buttonDialogScreen_1 = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonDialogScreen_1.setEnabled(True)
        self.buttonDialogScreen_1.setGeometry(QtCore.QRect(244, 342, 156, 23))
        self.buttonDialogScreen_1.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonDialogScreen_1.setCenterButtons(False)
        self.buttonDialogScreen_1.setObjectName("buttonDialogScreen_1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 250, 211, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(51, 248, 155, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.OffAllScreen = QtWidgets.QRadioButton(self.centralwidget)
        self.OffAllScreen.setGeometry(QtCore.QRect(312, 256, 102, 17))
        self.OffAllScreen.setObjectName("OffAllScreen")
        self.OnAllScreen = QtWidgets.QRadioButton(self.centralwidget)
        self.OnAllScreen.setGeometry(QtCore.QRect(212, 256, 94, 17))
        self.OnAllScreen.setObjectName("OnAllScreen")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MonitorManagment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MonitorManagment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuRe = QtWidgets.QMenu(self.menubar)
        self.menuRe.setObjectName("menuRe")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MonitorManagment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MonitorManagment)
        self.statusbar.setObjectName("statusbar")
        MonitorManagment.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MonitorManagment)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MonitorManagment)
        self.actionOpen.setObjectName("actionOpen")
        self.action_5 = QtWidgets.QAction(MonitorManagment)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MonitorManagment)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MonitorManagment)
        self.action_8.setObjectName("action_8")
        self.menuRe.addAction(self.action_5)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuRe.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MonitorManagment)
        QtCore.QMetaObject.connectSlotsByName(MonitorManagment)

    def retranslateUi(self, MonitorManagment):
        _translate = QtCore.QCoreApplication.translate
        MonitorManagment.setWindowTitle(_translate("MonitorManagment", "MonitorManagment"))
        self.ProjectorIndicator.setText(_translate("MonitorManagment", "ПРОЕКТОР"))
        self.label_2.setText(_translate("MonitorManagment", "Проектор"))
        self.ScreenIndicator_2.setText(_translate("MonitorManagment", "2 Экран Включить?"))
        self.ScreenIndicator_1.setText(_translate("MonitorManagment", "1 Экран Включить?"))
        self.ScreenIndicator_3.setText(_translate("MonitorManagment", "3 Экран Включить?"))
        self.label.setText(_translate("MonitorManagment", "Главный зал"))
        self.OffAllScreen.setText(_translate("MonitorManagment", "Выключить все"))
        self.OnAllScreen.setText(_translate("MonitorManagment", "Включить все"))
        self.pushButton.setText(_translate("MonitorManagment", "Применить"))
        self.menuRe.setTitle(_translate("MonitorManagment", "Настройки"))
        self.menu.setTitle(_translate("MonitorManagment", "Служба техподдержки"))
        self.menu_2.setTitle(_translate("MonitorManagment", "Отправить Дмитрию сообщение"))
        self.actionClose.setText(_translate("MonitorManagment", "Close"))
        self.actionOpen.setText(_translate("MonitorManagment", "Open"))
        self.action_5.setText(_translate("MonitorManagment", "Тест"))
        self.action_7.setText(_translate("MonitorManagment", "\"Вышла ошибка\""))
        self.action_8.setText(_translate("MonitorManagment", "\"Монитор или проектор не запустился\""))

